name: Repository Dispatch
on:
  repository_dispatch:
    types: [update-all]
jobs:
  UpdateAll:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.client_payload.ref }}
      - run: ./update_all.ps1
