name: Repository Dispatch
on:
  repository_dispatch:
    types: [update-all]
jobs:
  UpdateAll:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.client_payload.ref }}
      - name: Configure git credentials
        uses: OleksiyRudenko/gha-git-credentials@v2.1.1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
      - run: ./update_all.ps1
