name: Repository Dispatch
on:
  repository_dispatch:
    types: [update-all]
jobs:
  UpdateAll:
    runs-on: windows-latest
    steps:
      - name: Configure git credentials
        uses: OleksiyRudenko/gha-git-credentials@v2.1.1
        with:
          token: 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
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.client_payload.ref }}
      - run: ./update_all.ps1
